# Agenda

- Simple programs
- control statement
- Indentation
- Control Flow
    - conditional Statements
        - If statement
        - if-elif statement
        - is-else statement
    - Loops
        - While loop
        - For loop
        - Nested loop
        - infinite Loops
        - else suite
-  Statements
    - break
    - pass
    - assert
    - yield
    - return

# Simple Programs

- A simple program in Python often involves basic operations like arithmetic calculations, printing messages, or taking user input. 
- It typically consists of a sequence of statements that are executed in a linear manner.
- Here's an example of a simple Python program that calculates the sum of two numbers:

In [47]:
# Simple program to calculate the sum of two numbers

# Input
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Calculation
sum = num1 + num2

# Output
print("The sum of", num1, "and", num2, "is", sum)

Enter the first number: 56
Enter the second number: 65
The sum of 56.0 and 65.0 is 121.0

# Control Statements

- Control statements in Python are programming constructs that control the flow of execution in a program.
- They enable you to dictate the order in which statements are executed based on certain conditions or loops.

**The three main types of control statements in Python are:**

- **Conditional Statements** (if, elif, else)
- **Looping Statements** (for, while)
- **Control Transfer Statements** (break, continue, pass)

# Indentation

- Indentation in Python is a crucial aspect of its syntax and plays a fundamental role in defining the structure of code blocks.
- Unlike many other programming languages that use braces `{}` or keywords like `begin` and `end` to denote blocks of code, **Python uses indentation to indicate the beginning and end of blocks**.
- The Python interpreter determines the structure of the code solely based on the indentation level.

A detailed explanation on overview of **indentation** in Python:

1. **Indentation Levels:**
   - Indentation refers to the spaces or tabs that precede lines of code.
   - All statements within the same block must have the same indentation level.
   - Common practice in Python is to use four spaces for each level of indentation, although tabs or any consistent number of spaces can also be used.

2. **Indentation for Code Blocks:**
   - Indentation is primarily used to define code blocks, such as those within functions, loops, conditional statements, and class definitions.
   - A colon `:` at the end of a line is typically followed by an indented block of code.
   - The indented block of code represents the body of the block (e.g., conditional statements, function body, loop body, etc.).

3. **Indentation Error:**
   - Incorrect indentation can lead to syntax errors or alter the intended logic of the program.
   - Python relies on indentation consistency for interpreting code structure, so mixing tabs and spaces or using inconsistent indentation levels will result in an indentation error.

4. **Nested Blocks:**
   - Python allows nesting of code blocks within each other.
   - Inner blocks are indented further than their containing blocks.
   - Nested blocks can be used within functions, loops, conditional statements, etc.

5. **End of Blocks:**
   - Dedentation (reducing the indentation level) marks the end of a code block.
   - Dedentation is used to indicate that a block of code has finished.
   - The end of a block is determined by returning to the previous indentation level or by reaching the left margin of the code.

In [51]:
# Example of indentation in Python
def greet(name):
    if name == "Alice":
        print("if part executed","Hello, Alice!")
    else:
        print("else part executed. ","Hello, " + name + "!")
    print("this will be printed every time.","Welcome to Python!")

- In the example above, the `if` statement and the `else` block are indented to the same level within the `greet` function. 
- The `print("Welcome to Python!")` statement is at the same indentation level as the `if` and `else` blocks, indicating that it is outside both blocks. 

- Overall, indentation is a distinctive feature of Python syntax that enhances readability and encourages consistent coding practices.

In [52]:
greet("Rohit")

else part executed.  Hello, Rohit!
this will be printed every time. Welcome to Python!

In [53]:
greet("Alice")

if part executed Hello, Alice!
this will be printed every time. Welcome to Python!

# 1. Conditional Statements

**Conditional statements in Python are used to execute certain blocks of code based on whether a given condition is true or false.**
- The primary conditional statements in Python are 
    - **'if'**,
    - **'elif'** (short for "else if"), and
    - **'else'**.

## 1.1. **if Statement:**

- The `if` statement is used to execute a block of code if a specified condition is true.

In [ ]:
# Syntax:
if condition:
    # Code block to execute if condition is true

In [59]:
# Example:
x = int(input("Enter a number\n"))
type(x)
if x > 5:
    print("x is greater than 5")

Enter a number
10
x is greater than 5

- **Explanation**
    - In this example, the `if` statement checks whether the value of 'x' is greater than 5.
    - If the condition is true (which it is, since `x` is 10), 
    - the indented block of code (`print("x is greater than 5")`) is executed.

## 1.2. **elif Statement:**

- The `elif` statement allows you to check additional conditions if the preceding `if` statement(s) evaluate to false.

In [ ]:
# Syntax:
if condition1:
    # Code block to execute if condition1 is true
elif condition2:
    # Code block to execute if condition2 is true and condition1 is false
elif condition3:
    # Code block to execute if condition3 is true and condition1 condition2 is false

In [63]:
# Example
x = int(input('Enter a number: '))
if x > 10:
    print("x is greater than 10")
elif x < 10:
    print("x is less than 10")
# elif x == 10:
#     print("x is equal to 10")

Enter a number: 10

In [65]:
# Example
x = int(input('Enter a number: '))
if x > 10:
    print("x is greater than 10")
elif x < 10:
    print("x is less than 10")
# elif x == 10:
#     print("x is equal to 10")

Enter a number: 90
x is greater than 10

**Explanation**
- In this example, the `elif` statement checks whether `x` is less than 10 after the `if` condition (`x > 10`) evaluates to false.
- Since `x` is not greater than 10 and it's also not less than 10, the `else` block executes, printing "x is equal to 10".

## 1.3. **else Statement:**

- The `else` statement is used to execute a block of code if none of the preceding conditions (in `if` or `elif` statements) evaluate to true.

In [ ]:
# Syntax
if condition:
    # Code block to execute if condition is true
else:
    # Code block to execute if condition is false

In [70]:
# Example
x = int(input("Enter a number: "))
if x > 10:
    print("If executed. ","x is greater than 10")
elif x==10:
    print("Elif Executed. ","x is equal to 10")
else:
    print("Else executed. ","x is not greater than 10")

Enter a number: -12
Else executed.  x is not greater than 10

**Explanation**

- In this example, since the condition `x > 10` is false (as `x` is 5), the code block under `else` is executed, printing "x is not greater than 10".
- These conditional statements provide the ability to control the flow of execution in Python programs based on various conditions, allowing for more flexible and dynamic behavior.

## Examples - Conditional Statements

###  Level 1

#### 1. Check if a number is positive, negative, or zero:

In [76]:
num = float(input("Enter a number: "))
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

Enter a number: 23
Positive

#### 2. Check if a user's age is a minor, adult, or invalid:

In [79]:
age = int(input("Enter your age: "))
if age < 0:
    print("Invalid age")
elif age < 18:
    print("You are a minor")
else:
    print("You are an adult")

Enter your age: 12
You are a minor

#### 3. Determine if a year is a leap year:

In [81]:
year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, " is a Leap year")
else:
    print(year, "is not a Leap year")

Enter a year: 2024
2024  is a Leap year

### Level 2

#### 4. Check if a user's exam score indicates pass or fail:

In [83]:
score = int(input("Enter your exam score: "))

if score >= 60:
    print("You passed")
else:
    print("You failed")

Enter your exam score: 90
You passed

#### 5. Determine if a number is even or odd:

In [13]:
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Enter a number: 23
Odd

#### 6. Find the largest number among three input numbers:

In [14]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

largest = max(num1, num2, num3)
print("The largest number is:", largest)

Enter the first number: 23
Enter the second number: 45
Enter the third number: 12
The largest number is: 45.0

###  Level 3

#### 7. Determine the type of triangle based on given side lengths:

In [16]:
a = float(input("Enter the length of side a: "))
b = float(input("Enter the length of side b: "))
c = float(input("Enter the length of side c: "))

if a == b == c:
    print("Equilateral triangle")
elif a == b or b == c or c == a:
    print("Isosceles triangle")
else:
    print("Scalene triangle")

Enter the length of side a: 12
Enter the length of side b: 34
Enter the length of side c: 12
Isosceles triangle

#### 8. Simulate a simple login system:

In [18]:
username = input("Enter your username: ")
password = input("Enter your password: ")

if username == "admin" and password == "password123":
    print("Login successful")
else:
    print("Invalid credentials")

Enter your username: admin
Enter your password: password123
Login successful

#### 9. Check if a year is a century year or not:

In [19]:
year = int(input("Enter a year: "))

if year % 100 == 0:
    print("Century year")
else:
    print("Not a century year")

Enter a year: 2000
Century year

### Level 4

1. **Grade Classifier**
Write a Python program that takes a student's exam score as input and classifies it into different grade categories based on the following criteria:

- Score ≥ 90: "A"
- 80 ≤ Score < 90: "B"
- 70 ≤ Score < 80: "C"
- 60 ≤ Score < 70: "D"
- Score < 60: "F"

In [20]:
score = int(input("Enter your exam score: "))

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"

print("Your grade is:", grade)

Enter your exam score: 89
Your grade is: B

2. **Ticket Price Calculator**
Write a Python program that prompts the user for their age and determines the ticket price for a movie based on the following age categories:

- Age < 3: Free
- 3 ≤ Age < 12: \$10
- 12 ≤ Age < 18: \$15
- 18 ≤ Age < 65: \$20
- Age ≥ 65: \$12

In [21]:
age = int(input("Enter your age: "))

if age < 3:
    price = "Free"
elif age < 12:
    price = "$10"
elif age < 18:
    price = "$15"
elif age < 65:
    price = "$20"
else:
    price = "$12"

print("Ticket price:", price)

Enter your age: 5
Ticket price: $10

3. **ATM Withdrawal Limit**
Write a Python program that simulates an ATM withdrawal and determines the maximum amount of cash that can be withdrawn based on the following withdrawal limits:

- Balance < \$100: \$20
- \$100 ≤ Balance < \$500: \$50
- \$500 ≤ Balance < \$1000: \$100
- Balance ≥ \$1000: \$200

In [22]:
balance = float(input("Enter your account balance: "))

if balance < 100:
    withdrawal_limit = "$20"
elif balance < 500:
    withdrawal_limit = "$50"
elif balance < 1000:
    withdrawal_limit = "$100"
else:
    withdrawal_limit = "$200"

print("Maximum withdrawal limit:", withdrawal_limit)

Enter your account balance: 23
Maximum withdrawal limit: $20

# 2. Looping Statements

## 2.1. While Loop

- The `while` loop in Python is used to repeatedly execute a block of code as long as a specified condition evaluates to true.
- It's a fundamental control flow structure that allows for iteration or looping based on the satisfaction of a condition.

In [ ]:
# Syntax
while condition:
    # Code block to execute while condition is true
    # This block can contain any number of statements

- The `while` keyword is followed by the condition that needs to be checked before each iteration.
- The colon `:` marks the beginning of the code block associated with the loop.
- The code block is indented and contains the statements that will be executed repeatedly as long as the condition remains true.

#### Execution Flow:
1. The condition is evaluated before entering the loop. 
    1. If the condition is initially false, the code block inside the loop is not executed, and the program moves on to the next statement after the loop.
2. If the condition is true, the code block inside the loop is executed.
3. After the code block executes, the condition is evaluated again.
    1. If it's still true, the code block is executed again. 
    2. This process continues until the condition becomes false.
4. Once the condition evaluates to false, the execution of the loop terminates, and control passes to the next statement after the loop.

In [1]:
# Example: Counting from 1 to 5 using a while loop
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5

#### Explanation
- In this example, the `count` variable is initialized to 1.
- The `while` loop checks whether `count` is less than or equal to 5.
- As long as `count` is less than or equal to 5, the loop executes the code block inside it, which prints the current value of `count` and increments `count` by 1.
- The loop continues until `count` becomes 6, at which point the condition `count <= 5` evaluates to false, and the loop terminates.

### Key Points:
- The condition in a `while` loop is checked before each iteration.
- If the condition is initially false, the loop will not execute at all.
- Be cautious when using `while` loops to avoid infinite loops, where the condition never becomes false, resulting in the loop executing indefinitely.
- It's essential to ensure that the condition eventually becomes false to prevent infinite loops.
- `while` loops are suitable for scenarios where the **number of iterations is not known beforehand** or when **you want to repeat a block of code until a certain condition is met.**

## 2.2. Questions

### level 1

1. **Countdown Timer:**
   Write a Python program that prompts the user to enter a number and then counts down from that number to 1, printing each number along the way.

In [3]:
# Solution 1
num = int(input("Enter a number: "))
while num > 0:
    print(num)
    num -= 1

Enter a number: 1000
1000
999
998
997
996
995
994
993
992
991
990
989
988
987
986
985
984
983
982
981
980
979
978
977
976
975
974
973
972
971
970
969
968
967
966
965
964
963
962
961
960
959
958
957
956
955
954
953
952
951
950
949
948
947
946
945
944
943
942
941
940
939
938
937
936
935
934
933
932
931
930
929
928
927
926
925
924
923
922
921
920
919
918
917
916
915
914
913
912
911
910
909
908
907
906
905
904
903
902
901
900
899
898
897
896
895
894
893
892
891
890
889
888
887
886
885
884
883
882
881
880
879
878
877
876
875
874
873
872
871
870
869
868
867
866
865
864
863
862
861
860
859
858
857
856
855
854
853
852
851
850
849
848
847
846
845
844
843
842
841
840
839
838
837
836
835
834
833
832
831
830
829
828
827
826
825
824
823
822
821
820
819
818
817
816
815
814
813
812
811
810
809
808
807
806
805
804
803
802
801
800
799
798
797
796
795
794
793
792
791
790
789
788
787
786
785
784
783
782
781
780
779
778
777
776
775
774
773
772
771
770
769
768
767
766
765
764
763
762
761
760
759
758
757
756
755
754
753
752
751
750
749
748
747
746
745
744
743
742
741
740
739
738
737
736
735
734
733
732
731
730
729
728
727
726
725
724
723
722
721
720
719
718
717
716
715
714
713
712
711
710
709
708
707
706
705
704
703
702
701
700
699
698
697
696
695
694
693
692
691
690
689
688
687
686
685
684
683
682
681
680
679
678
677
676
675
674
673
672
671
670
669
668
667
666
665
664
663
662
661
660
659
658
657
656
655
654
653
652
651
650
649
648
647
646
645
644
643
642
641
640
639
638
637
636
635
634
633
632
631
630
629
628
627
626
625
624
623
622
621
620
619
618
617
616
615
614
613
612
611
610
609
608
607
606
605
604
603
602
601
600
599
598
597
596
595
594
593
592
591
590
589
588
587
586
585
584
583
582
581
580
579
578
577
576
575
574
573
572
571
570
569
568
567
566
565
564
563
562
561
560
559
558
557
556
555
554
553
552
551
550
549
548
547
546
545
544
543
542
541
540
539
538
537
536
535
534
533
532
531
530
529
528
527
526
525
524
523
522
521
520
519
518
517
516
515
514
513
512
511
510
509
508
507
506
505
504
503
502
501
500
499
498
497
496
495
494
493
492
491
490
489
488
487
486
485
484
483
482
481
480
479
478
477
476
475
474
473
472
471
470
469
468
467
466
465
464
463
462
461
460
459
458
457
456
455
454
453
452
451
450
449
448
447
446
445
444
443
442
441
440
439
438
437
436
435
434
433
432
431
430
429
428
427
426
425
424
423
422
421
420
419
418
417
416
415
414
413
412
411
410
409
408
407
406
405
404
403
402
401
400
399
398
397
396
395
394
393
392
391
390
389
388
387
386
385
384
383
382
381
380
379
378
377
376
375
374
373
372
371
370
369
368
367
366
365
364
363
362
361
360
359
358
357
356
355
354
353
352
351
350
349
348
347
346
345
344
343
342
341
340
339
338
337
336
335
334
333
332
331
330
329
328
327
326
325
324
323
322
321
320
319
318
317
316
315
314
313
312
311
310
309
308
307
306
305
304
303
302
301
300
299
298
297
296
295
294
293
292
291
290
289
288
287
286
285
284
283
282
281
280
279
278
277
276
275
274
273
272
271
270
269
268
267
266
265
264
263
262
261
260
259
258
257
256
255
254
253
252
251
250
249
248
247
246
245
244
243
242
241
240
239
238
237
236
235
234
233
232
231
230
229
228
227
226
225
224
223
222
221
220
219
218
217
216
215
214
213
212
211
210
209
208
207
206
205
204
203
202
201
200
199
198
197
196
195
194
193
192
191
190
189
188
187
186
185
184
183
182
181
180
179
178
177
176
175
174
173
172
171
170
169
168
167
166
165
164
163
162
161
160
159
158
157
156
155
154
153
152
151
150
149
148
147
146
145
144
143
142
141
140
139
138
137
136
135
134
133
132
131
130
129
128
127
126
125
124
123
122
121
120
119
118
117
116
115
114
113
112
111
110
109
108
107
106
105
104
103
102
101
100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1

2. **Password Guessing Game:**
   Create a Python program that asks the user to guess a secret password (e.g., "password123"). The program should continue prompting the user for input until they correctly guess the password.

In [4]:
password = "password123"
guess = input("Guess the password: ")
while guess != password:
    guess = input("Incorrect. Try again: ")
print("Congratulations! You guessed the password.")

Guess the password: password
Incorrect. Try again: pass
Incorrect. Try again: abc123
Incorrect. Try again: password123
Congratulations! You guessed the password.

### Level 2

3. **Factorial Calculator:**
   Write a Python program that prompts the user to enter a positive integer and calculates its factorial using a while loop. The factorial of a number is the product of all positive integers less than or equal to that number.

In [5]:
num = int(input("Enter a positive integer: "))
factorial = 1
while num > 0:
    factorial *= num
    num -= 1
print("Factorial:", factorial)

Enter a positive integer: 6
Factorial: 720

4. **Number Guessing Game with Limited Attempts:**
   Develop a Python program that generates a random number between 1 and 100 and asks the user to guess it. The program should give the user a maximum of 5 attempts to guess the number correctly. After each incorrect guess, the program should provide a hint whether the actual number is higher or lower.

In [6]:
import random

In [15]:
random.randint(12,14)

12

In [17]:
import random
secret_number = random.randint(1, 100)
attempts = 0
while attempts < 5:
    guess = int(input("Guess the number (1-100): "))
    attempts += 1
    if guess == secret_number:
        print("Congratulations! You guessed the number in", attempts, "attempts.")
        break
    elif guess < secret_number:
        print("Too low. Try again.")
    else:
        print("Too high. Try again.")
else:
    print("You've used all your attempts. The correct number was", secret_number)

Guess the number (1-100): 30
Too high. Try again.
Guess the number (1-100): 20
Too low. Try again.
Guess the number (1-100): 25
Congratulations! You guessed the number in 3 attempts.

5. **Sum of Digits:**
   Create a Python program that prompts the user to enter a positive integer and calculates the sum of its digits using a while loop. For example, if the input is 12345, the program should calculate and print the sum as 15 (1 + 2 + 3 + 4 + 5).

In [28]:
num = int(input("Enter a positive integer: "))
total = 0
while num > 0:
    total += num % 10
    num //= 10
print("Sum of digits:", total)

Enter a positive integer: 3
Sum of digits: 3

## 2.2. Infinite Loop

- An infinite loop in Python is a loop that continues to execute indefinitely because the loop's exit condition is never met.
- This can happen accidentally due to programming errors or intentionally when the program is designed to run continuously until stopped externally. 
- Infinite loops are often encountered when using while loops, although they can occur with other loop types as well.

#### 2.2.1. Characteristics of an Infinite Loop:

1. **No Exit Condition:** 
    - An infinite loop lacks a proper exit condition that would cause the loop to terminate.
    - Without a condition that can evaluate to false, the loop continues indefinitely.

2. **Continuously Executing Code:**
    - The code block inside an infinite loop executes repeatedly without interruption.
    - This can lead to high CPU usage and may cause the program to become unresponsive.

### 2.2.2. Causes of Infinite Loops:

1. **Logic Errors:**
    - Programming mistakes, such as incorrectly written loop conditions or incorrect loop control variable updates, can lead to infinite loops.

2. **Intentional Design:** 
    - In some cases, an infinite loop may be intentionally designed into the program to create a continuously running process, such as a server waiting for incoming connections or a program monitoring system events.

In [ ]:
# Example of an accidental infinite loop
num = 1
while num > 0:
    print(num)
    num += 1

In this example, the loop condition `num > 0` will always be true because `num` is initialized to 1 and incremented with each iteration. As a result, the loop will continue indefinitely, printing increasing numbers to the console.

### 2.2.3. Dealing with Infinite Loops:

1. **Manual Termination:** 
    - If an infinite loop occurs during program execution, you may need to terminate the program manually.
    - This can be done by interrupting the program's execution through the terminal or the integrated development environment (IDE).

In [18]:
import pdb

2. **Debugger:** 
    - Debugging tools, such as breakpoints and step-by-step execution, can help identify the cause of an infinite loop by allowing you to inspect the program's state and execution flow.

3. **Careful Programming:** 
    - To prevent accidental infinite loops, carefully review loop conditions and ensure that they will eventually evaluate to false.
    - Additionally, use loop control mechanisms such as `break` statements or loop counters to provide exit points when needed.

4. **Testing:** 
    - Thoroughly test your code to identify and fix any potential issues related to infinite loops before deploying the program into production.

## 3. For Loop

- A `for` loop in Python is used to iterate over a sequence (such as a list, tuple, string, or range) and execute a block of code for each item in the sequence.
- It's a versatile and powerful tool for performing repetitive tasks and processing elements of collections.

In [ ]:
### Syntax:
for item in sequence:
    # Code block to execute for each item in the sequence
    # This block can contain any number of statements

- The `for` keyword is followed by a loop variable (`item` in the syntax) that represents each item in the sequence during each iteration.
- The `in` keyword is used to specify the sequence over which the loop iterates.
- The colon `:` marks the beginning of the code block associated with the loop.
- The code block is indented and contains the statements that will be executed for each item in the sequence.

### 3.1. Execution Flow

1. The loop variable (`item` in the syntax) takes on each value in the sequence, one at a time, in the order they appear in the sequence.
2. For each value of the loop variable, the code block inside the loop is executed.
3. After executing the code block for each item in the sequence, the loop completes, and control passes to the next statement after the loop.

In [19]:
# Example: Iterate over a list of fruits and print each fruit
fruits = ["apple", "banana", "cherry"]

In [20]:
type(fruits)

list

In [22]:
for fruit in fruits:
    print(fruit)

apple
banana
cherry

**Explanation**
- In this example, the `fruits` list contains three items: "apple", "banana", and "cherry".
- The `for` loop iterates over each item in the `fruits` list, assigning the loop variable `fruit` to each item in turn.
- For each iteration, the code block inside the loop (`print(fruit)`) is executed, printing the value of `fruit` to the console.

### 3.2. Key Points

- The sequence over which a `for` loop iterates can be any **iterable object**, including **lists, tuples, strings, dictionaries (for keys or values), sets, and even custom iterable objects.**
- The loop variable (`item` in the syntax) takes on the value of each item in the sequence during each iteration of the loop.
- `for` loops are suitable for scenarios where the number of iterations is known or can be determined in advance, such as iterating over elements in a collection or performing a fixed number of iterations.

### Questions

#### Iterating over a String

In [30]:
word = "Python"
for char in word:
    print(char)

P
y
t
h
o
n

#### Iterating over a Dictionary

In [31]:
student_grades = {"Alice": 85, "Bob": 72, "Charlie": 90}
for name, grade in student_grades.items():
    print(name, ":", grade)

Alice : 85
Bob : 72
Charlie : 90

#### Nested Loop

In [26]:
for i in range(1, 101):
    print('\n')
    for j in range(1, 21):
        print(i, "x", j, "=", i * j)

1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10
1 x 11 = 11
1 x 12 = 12
1 x 13 = 13
1 x 14 = 14
1 x 15 = 15
1 x 16 = 16
1 x 17 = 17
1 x 18 = 18
1 x 19 = 19
1 x 20 = 20


2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
2 x 11 = 22
2 x 12 = 24
2 x 13 = 26
2 x 14 = 28
2 x 15 = 30
2 x 16 = 32
2 x 17 = 34
2 x 18 = 36
2 x 19 = 38
2 x 20 = 40


3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30
3 x 11 = 33
3 x 12 = 36
3 x 13 = 39
3 x 14 = 42
3 x 15 = 45
3 x 16 = 48
3 x 17 = 51
3 x 18 = 54
3 x 19 = 57
3 x 20 = 60


4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
4 x 11 = 44
4 x 12 = 48
4 x 13 = 52
4 x 14 = 56
4 x 15 = 60
4 x 16 = 64
4 x 17 = 68
4 x 18 = 72
4 x 19 = 76
4 x 20 = 80


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
5 x 11 = 55
5 x 12 = 60
5 x 13 = 65
5 x 14 = 70
5 x 15 = 75
5 x 16 = 80
5 x 17 = 85
5 x 18 = 90
5 x 19 = 95
5 x 20 = 100


6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60
6 x 11 = 66
6 x 12 = 72
6 x 13 = 78
6 x 14 = 84
6 x 15 = 90
6 x 16 = 96
6 x 17 = 102
6 x 18 = 108
6 x 19 = 114
6 x 20 = 120


7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
7 x 11 = 77
7 x 12 = 84
7 x 13 = 91
7 x 14 = 98
7 x 15 = 105
7 x 16 = 112
7 x 17 = 119
7 x 18 = 126
7 x 19 = 133
7 x 20 = 140


8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80
8 x 11 = 88
8 x 12 = 96
8 x 13 = 104
8 x 14 = 112
8 x 15 = 120
8 x 16 = 128
8 x 17 = 136
8 x 18 = 144
8 x 19 = 152
8 x 20 = 160


9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90
9 x 11 = 99
9 x 12 = 108
9 x 13 = 117
9 x 14 = 126
9 x 15 = 135
9 x 16 = 144
9 x 17 = 153
9 x 18 = 162
9 x 19 = 171
9 x 20 = 180


10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100
10 x 11 = 110
10 x 12 = 120
10 x 13 = 130
10 x 14 = 140
10 x 15 = 150
10 x 16 = 160
10 x 17 = 170
10 x 18 = 180
10 x 19 = 190
10 x 20 = 200


11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110
11 x 11 = 121
11 x 12 = 132
11 x 13 = 143
11 x 14 = 154
11 x 15 = 165
11 x 16 = 176
11 x 17 = 187
11 x 18 = 198
11 x 19 = 209
11 x 20 = 220


12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120
12 x 11 = 132
12 x 12 = 144
12 x 13 = 156
12 x 14 = 168
12 x 15 = 180
12 x 16 = 192
12 x 17 = 204
12 x 18 = 216
12 x 19 = 228
12 x 20 = 240


13 x 1 = 13
13 x 2 = 26
13 x 3 = 39
13 x 4 = 52
13 x 5 = 65
13 x 6 = 78
13 x 7 = 91
13 x 8 = 104
13 x 9 = 117
13 x 10 = 130
13 x 11 = 143
13 x 12 = 156
13 x 13 = 169
13 x 14 = 182
13 x 15 = 195
13 x 16 = 208
13 x 17 = 221
13 x 18 = 234
13 x 19 = 247
13 x 20 = 260


14 x 1 = 14
14 x 2 = 28
14 x 3 = 42
14 x 4 = 56
14 x 5 = 70
14 x 6 = 84
14 x 7 = 98
14 x 8 = 112
14 x 9 = 126
14 x 10 = 140
14 x 11 = 154
14 x 12 = 168
14 x 13 = 182
14 x 14 = 196
14 x 15 = 210
14 x 16 = 224
14 x 17 = 238
14 x 18 = 252
14 x 19 = 266
14 x 20 = 280


15 x 1 = 15
15 x 2 = 30
15 x 3 = 45
15 x 4 = 60
15 x 5 = 75
15 x 6 = 90
15 x 7 = 105
15 x 8 = 120
15 x 9 = 135
15 x 10 = 150
15 x 11 = 165
15 x 12 = 180
15 x 13 = 195
15 x 14 = 210
15 x 15 = 225
15 x 16 = 240
15 x 17 = 255
15 x 18 = 270
15 x 19 = 285
15 x 20 = 300


16 x 1 = 16
16 x 2 = 32
16 x 3 = 48
16 x 4 = 64
16 x 5 = 80
16 x 6 = 96
16 x 7 = 112
16 x 8 = 128
16 x 9 = 144
16 x 10 = 160
16 x 11 = 176
16 x 12 = 192
16 x 13 = 208
16 x 14 = 224
16 x 15 = 240
16 x 16 = 256
16 x 17 = 272
16 x 18 = 288
16 x 19 = 304
16 x 20 = 320


17 x 1 = 17
17 x 2 = 34
17 x 3 = 51
17 x 4 = 68
17 x 5 = 85
17 x 6 = 102
17 x 7 = 119
17 x 8 = 136
17 x 9 = 153
17 x 10 = 170
17 x 11 = 187
17 x 12 = 204
17 x 13 = 221
17 x 14 = 238
17 x 15 = 255
17 x 16 = 272
17 x 17 = 289
17 x 18 = 306
17 x 19 = 323
17 x 20 = 340


18 x 1 = 18
18 x 2 = 36
18 x 3 = 54
18 x 4 = 72
18 x 5 = 90
18 x 6 = 108
18 x 7 = 126
18 x 8 = 144
18 x 9 = 162
18 x 10 = 180
18 x 11 = 198
18 x 12 = 216
18 x 13 = 234
18 x 14 = 252
18 x 15 = 270
18 x 16 = 288
18 x 17 = 306
18 x 18 = 324
18 x 19 = 342
18 x 20 = 360


19 x 1 = 19
19 x 2 = 38
19 x 3 = 57
19 x 4 = 76
19 x 5 = 95
19 x 6 = 114
19 x 7 = 133
19 x 8 = 152
19 x 9 = 171
19 x 10 = 190
19 x 11 = 209
19 x 12 = 228
19 x 13 = 247
19 x 14 = 266
19 x 15 = 285
19 x 16 = 304
19 x 17 = 323
19 x 18 = 342
19 x 19 = 361
19 x 20 = 380


20 x 1 = 20
20 x 2 = 40
20 x 3 = 60
20 x 4 = 80
20 x 5 = 100
20 x 6 = 120
20 x 7 = 140
20 x 8 = 160
20 x 9 = 180
20 x 10 = 200
20 x 11 = 220
20 x 12 = 240
20 x 13 = 260
20 x 14 = 280
20 x 15 = 300
20 x 16 = 320
20 x 17 = 340
20 x 18 = 360
20 x 19 = 380
20 x 20 = 400


21 x 1 = 21
21 x 2 = 42
21 x 3 = 63
21 x 4 = 84
21 x 5 = 105
21 x 6 = 126
21 x 7 = 147
21 x 8 = 168
21 x 9 = 189
21 x 10 = 210
21 x 11 = 231
21 x 12 = 252
21 x 13 = 273
21 x 14 = 294
21 x 15 = 315
21 x 16 = 336
21 x 17 = 357
21 x 18 = 378
21 x 19 = 399
21 x 20 = 420


22 x 1 = 22
22 x 2 = 44
22 x 3 = 66
22 x 4 = 88
22 x 5 = 110
22 x 6 = 132
22 x 7 = 154
22 x 8 = 176
22 x 9 = 198
22 x 10 = 220
22 x 11 = 242
22 x 12 = 264
22 x 13 = 286
22 x 14 = 308
22 x 15 = 330
22 x 16 = 352
22 x 17 = 374
22 x 18 = 396
22 x 19 = 418
22 x 20 = 440


23 x 1 = 23
23 x 2 = 46
23 x 3 = 69
23 x 4 = 92
23 x 5 = 115
23 x 6 = 138
23 x 7 = 161
23 x 8 = 184
23 x 9 = 207
23 x 10 = 230
23 x 11 = 253
23 x 12 = 276
23 x 13 = 299
23 x 14 = 322
23 x 15 = 345
23 x 16 = 368
23 x 17 = 391
23 x 18 = 414
23 x 19 = 437
23 x 20 = 460


24 x 1 = 24
24 x 2 = 48
24 x 3 = 72
24 x 4 = 96
24 x 5 = 120
24 x 6 = 144
24 x 7 = 168
24 x 8 = 192
24 x 9 = 216
24 x 10 = 240
24 x 11 = 264
24 x 12 = 288
24 x 13 = 312
24 x 14 = 336
24 x 15 = 360
24 x 16 = 384
24 x 17 = 408
24 x 18 = 432
24 x 19 = 456
24 x 20 = 480


25 x 1 = 25
25 x 2 = 50
25 x 3 = 75
25 x 4 = 100
25 x 5 = 125
25 x 6 = 150
25 x 7 = 175
25 x 8 = 200
25 x 9 = 225
25 x 10 = 250
25 x 11 = 275
25 x 12 = 300
25 x 13 = 325
25 x 14 = 350
25 x 15 = 375
25 x 16 = 400
25 x 17 = 425
25 x 18 = 450
25 x 19 = 475
25 x 20 = 500


26 x 1 = 26
26 x 2 = 52
26 x 3 = 78
26 x 4 = 104
26 x 5 = 130
26 x 6 = 156
26 x 7 = 182
26 x 8 = 208
26 x 9 = 234
26 x 10 = 260
26 x 11 = 286
26 x 12 = 312
26 x 13 = 338
26 x 14 = 364
26 x 15 = 390
26 x 16 = 416
26 x 17 = 442
26 x 18 = 468
26 x 19 = 494
26 x 20 = 520


27 x 1 = 27
27 x 2 = 54
27 x 3 = 81
27 x 4 = 108
27 x 5 = 135
27 x 6 = 162
27 x 7 = 189
27 x 8 = 216
27 x 9 = 243
27 x 10 = 270
27 x 11 = 297
27 x 12 = 324
27 x 13 = 351
27 x 14 = 378
27 x 15 = 405
27 x 16 = 432
27 x 17 = 459
27 x 18 = 486
27 x 19 = 513
27 x 20 = 540


28 x 1 = 28
28 x 2 = 56
28 x 3 = 84
28 x 4 = 112
28 x 5 = 140
28 x 6 = 168
28 x 7 = 196
28 x 8 = 224
28 x 9 = 252
28 x 10 = 280
28 x 11 = 308
28 x 12 = 336
28 x 13 = 364
28 x 14 = 392
28 x 15 = 420
28 x 16 = 448
28 x 17 = 476
28 x 18 = 504
28 x 19 = 532
28 x 20 = 560


29 x 1 = 29
29 x 2 = 58
29 x 3 = 87
29 x 4 = 116
29 x 5 = 145
29 x 6 = 174
29 x 7 = 203
29 x 8 = 232
29 x 9 = 261
29 x 10 = 290
29 x 11 = 319
29 x 12 = 348
29 x 13 = 377
29 x 14 = 406
29 x 15 = 435
29 x 16 = 464
29 x 17 = 493
29 x 18 = 522
29 x 19 = 551
29 x 20 = 580


30 x 1 = 30
30 x 2 = 60
30 x 3 = 90
30 x 4 = 120
30 x 5 = 150
30 x 6 = 180
30 x 7 = 210
30 x 8 = 240
30 x 9 = 270
30 x 10 = 300
30 x 11 = 330
30 x 12 = 360
30 x 13 = 390
30 x 14 = 420
30 x 15 = 450
30 x 16 = 480
30 x 17 = 510
30 x 18 = 540
30 x 19 = 570
30 x 20 = 600


31 x 1 = 31
31 x 2 = 62
31 x 3 = 93
31 x 4 = 124
31 x 5 = 155
31 x 6 = 186
31 x 7 = 217
31 x 8 = 248
31 x 9 = 279
31 x 10 = 310
31 x 11 = 341
31 x 12 = 372
31 x 13 = 403
31 x 14 = 434
31 x 15 = 465
31 x 16 = 496
31 x 17 = 527
31 x 18 = 558
31 x 19 = 589
31 x 20 = 620


32 x 1 = 32
32 x 2 = 64
32 x 3 = 96
32 x 4 = 128
32 x 5 = 160
32 x 6 = 192
32 x 7 = 224
32 x 8 = 256
32 x 9 = 288
32 x 10 = 320
32 x 11 = 352
32 x 12 = 384
32 x 13 = 416
32 x 14 = 448
32 x 15 = 480
32 x 16 = 512
32 x 17 = 544
32 x 18 = 576
32 x 19 = 608
32 x 20 = 640


33 x 1 = 33
33 x 2 = 66
33 x 3 = 99
33 x 4 = 132
33 x 5 = 165
33 x 6 = 198
33 x 7 = 231
33 x 8 = 264
33 x 9 = 297
33 x 10 = 330
33 x 11 = 363
33 x 12 = 396
33 x 13 = 429
33 x 14 = 462
33 x 15 = 495
33 x 16 = 528
33 x 17 = 561
33 x 18 = 594
33 x 19 = 627
33 x 20 = 660


34 x 1 = 34
34 x 2 = 68
34 x 3 = 102
34 x 4 = 136
34 x 5 = 170
34 x 6 = 204
34 x 7 = 238
34 x 8 = 272
34 x 9 = 306
34 x 10 = 340
34 x 11 = 374
34 x 12 = 408
34 x 13 = 442
34 x 14 = 476
34 x 15 = 510
34 x 16 = 544
34 x 17 = 578
34 x 18 = 612
34 x 19 = 646
34 x 20 = 680


35 x 1 = 35
35 x 2 = 70
35 x 3 = 105
35 x 4 = 140
35 x 5 = 175
35 x 6 = 210
35 x 7 = 245
35 x 8 = 280
35 x 9 = 315
35 x 10 = 350
35 x 11 = 385
35 x 12 = 420
35 x 13 = 455
35 x 14 = 490
35 x 15 = 525
35 x 16 = 560
35 x 17 = 595
35 x 18 = 630
35 x 19 = 665
35 x 20 = 700


36 x 1 = 36
36 x 2 = 72
36 x 3 = 108
36 x 4 = 144
36 x 5 = 180
36 x 6 = 216
36 x 7 = 252
36 x 8 = 288
36 x 9 = 324
36 x 10 = 360
36 x 11 = 396
36 x 12 = 432
36 x 13 = 468
36 x 14 = 504
36 x 15 = 540
36 x 16 = 576
36 x 17 = 612
36 x 18 = 648
36 x 19 = 684
36 x 20 = 720


37 x 1 = 37
37 x 2 = 74
37 x 3 = 111
37 x 4 = 148
37 x 5 = 185
37 x 6 = 222
37 x 7 = 259
37 x 8 = 296
37 x 9 = 333
37 x 10 = 370
37 x 11 = 407
37 x 12 = 444
37 x 13 = 481
37 x 14 = 518
37 x 15 = 555
37 x 16 = 592
37 x 17 = 629
37 x 18 = 666
37 x 19 = 703
37 x 20 = 740


38 x 1 = 38
38 x 2 = 76
38 x 3 = 114
38 x 4 = 152
38 x 5 = 190
38 x 6 = 228
38 x 7 = 266
38 x 8 = 304
38 x 9 = 342
38 x 10 = 380
38 x 11 = 418
38 x 12 = 456
38 x 13 = 494
38 x 14 = 532
38 x 15 = 570
38 x 16 = 608
38 x 17 = 646
38 x 18 = 684
38 x 19 = 722
38 x 20 = 760


39 x 1 = 39
39 x 2 = 78
39 x 3 = 117
39 x 4 = 156
39 x 5 = 195
39 x 6 = 234
39 x 7 = 273
39 x 8 = 312
39 x 9 = 351
39 x 10 = 390
39 x 11 = 429
39 x 12 = 468
39 x 13 = 507
39 x 14 = 546
39 x 15 = 585
39 x 16 = 624
39 x 17 = 663
39 x 18 = 702
39 x 19 = 741
39 x 20 = 780


40 x 1 = 40
40 x 2 = 80
40 x 3 = 120
40 x 4 = 160
40 x 5 = 200
40 x 6 = 240
40 x 7 = 280
40 x 8 = 320
40 x 9 = 360
40 x 10 = 400
40 x 11 = 440
40 x 12 = 480
40 x 13 = 520
40 x 14 = 560
40 x 15 = 600
40 x 16 = 640
40 x 17 = 680
40 x 18 = 720
40 x 19 = 760
40 x 20 = 800


41 x 1 = 41
41 x 2 = 82
41 x 3 = 123
41 x 4 = 164
41 x 5 = 205
41 x 6 = 246
41 x 7 = 287
41 x 8 = 328
41 x 9 = 369
41 x 10 = 410
41 x 11 = 451
41 x 12 = 492
41 x 13 = 533
41 x 14 = 574
41 x 15 = 615
41 x 16 = 656
41 x 17 = 697
41 x 18 = 738
41 x 19 = 779
41 x 20 = 820


42 x 1 = 42
42 x 2 = 84
42 x 3 = 126
42 x 4 = 168
42 x 5 = 210
42 x 6 = 252
42 x 7 = 294
42 x 8 = 336
42 x 9 = 378
42 x 10 = 420
42 x 11 = 462
42 x 12 = 504
42 x 13 = 546
42 x 14 = 588
42 x 15 = 630
42 x 16 = 672
42 x 17 = 714
42 x 18 = 756
42 x 19 = 798
42 x 20 = 840


43 x 1 = 43
43 x 2 = 86
43 x 3 = 129
43 x 4 = 172
43 x 5 = 215
43 x 6 = 258
43 x 7 = 301
43 x 8 = 344
43 x 9 = 387
43 x 10 = 430
43 x 11 = 473
43 x 12 = 516
43 x 13 = 559
43 x 14 = 602
43 x 15 = 645
43 x 16 = 688
43 x 17 = 731
43 x 18 = 774
43 x 19 = 817
43 x 20 = 860


44 x 1 = 44
44 x 2 = 88
44 x 3 = 132
44 x 4 = 176
44 x 5 = 220
44 x 6 = 264
44 x 7 = 308
44 x 8 = 352
44 x 9 = 396
44 x 10 = 440
44 x 11 = 484
44 x 12 = 528
44 x 13 = 572
44 x 14 = 616
44 x 15 = 660
44 x 16 = 704
44 x 17 = 748
44 x 18 = 792
44 x 19 = 836
44 x 20 = 880


45 x 1 = 45
45 x 2 = 90
45 x 3 = 135
45 x 4 = 180
45 x 5 = 225
45 x 6 = 270
45 x 7 = 315
45 x 8 = 360
45 x 9 = 405
45 x 10 = 450
45 x 11 = 495
45 x 12 = 540
45 x 13 = 585
45 x 14 = 630
45 x 15 = 675
45 x 16 = 720
45 x 17 = 765
45 x 18 = 810
45 x 19 = 855
45 x 20 = 900


46 x 1 = 46
46 x 2 = 92
46 x 3 = 138
46 x 4 = 184
46 x 5 = 230
46 x 6 = 276
46 x 7 = 322
46 x 8 = 368
46 x 9 = 414
46 x 10 = 460
46 x 11 = 506
46 x 12 = 552
46 x 13 = 598
46 x 14 = 644
46 x 15 = 690
46 x 16 = 736
46 x 17 = 782
46 x 18 = 828
46 x 19 = 874
46 x 20 = 920


47 x 1 = 47
47 x 2 = 94
47 x 3 = 141
47 x 4 = 188
47 x 5 = 235
47 x 6 = 282
47 x 7 = 329
47 x 8 = 376
47 x 9 = 423
47 x 10 = 470
47 x 11 = 517
47 x 12 = 564
47 x 13 = 611
47 x 14 = 658
47 x 15 = 705
47 x 16 = 752
47 x 17 = 799
47 x 18 = 846
47 x 19 = 893
47 x 20 = 940


48 x 1 = 48
48 x 2 = 96
48 x 3 = 144
48 x 4 = 192
48 x 5 = 240
48 x 6 = 288
48 x 7 = 336
48 x 8 = 384
48 x 9 = 432
48 x 10 = 480
48 x 11 = 528
48 x 12 = 576
48 x 13 = 624
48 x 14 = 672
48 x 15 = 720
48 x 16 = 768
48 x 17 = 816
48 x 18 = 864
48 x 19 = 912
48 x 20 = 960


49 x 1 = 49
49 x 2 = 98
49 x 3 = 147
49 x 4 = 196
49 x 5 = 245
49 x 6 = 294
49 x 7 = 343
49 x 8 = 392
49 x 9 = 441
49 x 10 = 490
49 x 11 = 539
49 x 12 = 588
49 x 13 = 637
49 x 14 = 686
49 x 15 = 735
49 x 16 = 784
49 x 17 = 833
49 x 18 = 882
49 x 19 = 931
49 x 20 = 980


50 x 1 = 50
50 x 2 = 100
50 x 3 = 150
50 x 4 = 200
50 x 5 = 250
50 x 6 = 300
50 x 7 = 350
50 x 8 = 400
50 x 9 = 450
50 x 10 = 500
50 x 11 = 550
50 x 12 = 600
50 x 13 = 650
50 x 14 = 700
50 x 15 = 750
50 x 16 = 800
50 x 17 = 850
50 x 18 = 900
50 x 19 = 950
50 x 20 = 1000


51 x 1 = 51
51 x 2 = 102
51 x 3 = 153
51 x 4 = 204
51 x 5 = 255
51 x 6 = 306
51 x 7 = 357
51 x 8 = 408
51 x 9 = 459
51 x 10 = 510
51 x 11 = 561
51 x 12 = 612
51 x 13 = 663
51 x 14 = 714
51 x 15 = 765
51 x 16 = 816
51 x 17 = 867
51 x 18 = 918
51 x 19 = 969
51 x 20 = 1020


52 x 1 = 52
52 x 2 = 104
52 x 3 = 156
52 x 4 = 208
52 x 5 = 260
52 x 6 = 312
52 x 7 = 364
52 x 8 = 416
52 x 9 = 468
52 x 10 = 520
52 x 11 = 572
52 x 12 = 624
52 x 13 = 676
52 x 14 = 728
52 x 15 = 780
52 x 16 = 832
52 x 17 = 884
52 x 18 = 936
52 x 19 = 988
52 x 20 = 1040


53 x 1 = 53
53 x 2 = 106
53 x 3 = 159
53 x 4 = 212
53 x 5 = 265
53 x 6 = 318
53 x 7 = 371
53 x 8 = 424
53 x 9 = 477
53 x 10 = 530
53 x 11 = 583
53 x 12 = 636
53 x 13 = 689
53 x 14 = 742
53 x 15 = 795
53 x 16 = 848
53 x 17 = 901
53 x 18 = 954
53 x 19 = 1007
53 x 20 = 1060


54 x 1 = 54
54 x 2 = 108
54 x 3 = 162
54 x 4 = 216
54 x 5 = 270
54 x 6 = 324
54 x 7 = 378
54 x 8 = 432
54 x 9 = 486
54 x 10 = 540
54 x 11 = 594
54 x 12 = 648
54 x 13 = 702
54 x 14 = 756
54 x 15 = 810
54 x 16 = 864
54 x 17 = 918
54 x 18 = 972
54 x 19 = 1026
54 x 20 = 1080


55 x 1 = 55
55 x 2 = 110
55 x 3 = 165
55 x 4 = 220
55 x 5 = 275
55 x 6 = 330
55 x 7 = 385
55 x 8 = 440
55 x 9 = 495
55 x 10 = 550
55 x 11 = 605
55 x 12 = 660
55 x 13 = 715
55 x 14 = 770
55 x 15 = 825
55 x 16 = 880
55 x 17 = 935
55 x 18 = 990
55 x 19 = 1045
55 x 20 = 1100


56 x 1 = 56
56 x 2 = 112
56 x 3 = 168
56 x 4 = 224
56 x 5 = 280
56 x 6 = 336
56 x 7 = 392
56 x 8 = 448
56 x 9 = 504
56 x 10 = 560
56 x 11 = 616
56 x 12 = 672
56 x 13 = 728
56 x 14 = 784
56 x 15 = 840
56 x 16 = 896
56 x 17 = 952
56 x 18 = 1008
56 x 19 = 1064
56 x 20 = 1120


57 x 1 = 57
57 x 2 = 114
57 x 3 = 171
57 x 4 = 228
57 x 5 = 285
57 x 6 = 342
57 x 7 = 399
57 x 8 = 456
57 x 9 = 513
57 x 10 = 570
57 x 11 = 627
57 x 12 = 684
57 x 13 = 741
57 x 14 = 798
57 x 15 = 855
57 x 16 = 912
57 x 17 = 969
57 x 18 = 1026
57 x 19 = 1083
57 x 20 = 1140


58 x 1 = 58
58 x 2 = 116
58 x 3 = 174
58 x 4 = 232
58 x 5 = 290
58 x 6 = 348
58 x 7 = 406
58 x 8 = 464
58 x 9 = 522
58 x 10 = 580
58 x 11 = 638
58 x 12 = 696
58 x 13 = 754
58 x 14 = 812
58 x 15 = 870
58 x 16 = 928
58 x 17 = 986
58 x 18 = 1044
58 x 19 = 1102
58 x 20 = 1160


59 x 1 = 59
59 x 2 = 118
59 x 3 = 177
59 x 4 = 236
59 x 5 = 295
59 x 6 = 354
59 x 7 = 413
59 x 8 = 472
59 x 9 = 531
59 x 10 = 590
59 x 11 = 649
59 x 12 = 708
59 x 13 = 767
59 x 14 = 826
59 x 15 = 885
59 x 16 = 944
59 x 17 = 1003
59 x 18 = 1062
59 x 19 = 1121
59 x 20 = 1180


60 x 1 = 60
60 x 2 = 120
60 x 3 = 180
60 x 4 = 240
60 x 5 = 300
60 x 6 = 360
60 x 7 = 420
60 x 8 = 480
60 x 9 = 540
60 x 10 = 600
60 x 11 = 660
60 x 12 = 720
60 x 13 = 780
60 x 14 = 840
60 x 15 = 900
60 x 16 = 960
60 x 17 = 1020
60 x 18 = 1080
60 x 19 = 1140
60 x 20 = 1200


61 x 1 = 61
61 x 2 = 122
61 x 3 = 183
61 x 4 = 244
61 x 5 = 305
61 x 6 = 366
61 x 7 = 427
61 x 8 = 488
61 x 9 = 549
61 x 10 = 610
61 x 11 = 671
61 x 12 = 732
61 x 13 = 793
61 x 14 = 854
61 x 15 = 915
61 x 16 = 976
61 x 17 = 1037
61 x 18 = 1098
61 x 19 = 1159
61 x 20 = 1220


62 x 1 = 62
62 x 2 = 124
62 x 3 = 186
62 x 4 = 248
62 x 5 = 310
62 x 6 = 372
62 x 7 = 434
62 x 8 = 496
62 x 9 = 558
62 x 10 = 620
62 x 11 = 682
62 x 12 = 744
62 x 13 = 806
62 x 14 = 868
62 x 15 = 930
62 x 16 = 992
62 x 17 = 1054
62 x 18 = 1116
62 x 19 = 1178
62 x 20 = 1240


63 x 1 = 63
63 x 2 = 126
63 x 3 = 189
63 x 4 = 252
63 x 5 = 315
63 x 6 = 378
63 x 7 = 441
63 x 8 = 504
63 x 9 = 567
63 x 10 = 630
63 x 11 = 693
63 x 12 = 756
63 x 13 = 819
63 x 14 = 882
63 x 15 = 945
63 x 16 = 1008
63 x 17 = 1071
63 x 18 = 1134
63 x 19 = 1197
63 x 20 = 1260


64 x 1 = 64
64 x 2 = 128
64 x 3 = 192
64 x 4 = 256
64 x 5 = 320
64 x 6 = 384
64 x 7 = 448
64 x 8 = 512
64 x 9 = 576
64 x 10 = 640
64 x 11 = 704
64 x 12 = 768
64 x 13 = 832
64 x 14 = 896
64 x 15 = 960
64 x 16 = 1024
64 x 17 = 1088
64 x 18 = 1152
64 x 19 = 1216
64 x 20 = 1280


65 x 1 = 65
65 x 2 = 130
65 x 3 = 195
65 x 4 = 260
65 x 5 = 325
65 x 6 = 390
65 x 7 = 455
65 x 8 = 520
65 x 9 = 585
65 x 10 = 650
65 x 11 = 715
65 x 12 = 780
65 x 13 = 845
65 x 14 = 910
65 x 15 = 975
65 x 16 = 1040
65 x 17 = 1105
65 x 18 = 1170
65 x 19 = 1235
65 x 20 = 1300


66 x 1 = 66
66 x 2 = 132
66 x 3 = 198
66 x 4 = 264
66 x 5 = 330
66 x 6 = 396
66 x 7 = 462
66 x 8 = 528
66 x 9 = 594
66 x 10 = 660
66 x 11 = 726
66 x 12 = 792
66 x 13 = 858
66 x 14 = 924
66 x 15 = 990
66 x 16 = 1056
66 x 17 = 1122
66 x 18 = 1188
66 x 19 = 1254
66 x 20 = 1320


67 x 1 = 67
67 x 2 = 134
67 x 3 = 201
67 x 4 = 268
67 x 5 = 335
67 x 6 = 402
67 x 7 = 469
67 x 8 = 536
67 x 9 = 603
67 x 10 = 670
67 x 11 = 737
67 x 12 = 804
67 x 13 = 871
67 x 14 = 938
67 x 15 = 1005
67 x 16 = 1072
67 x 17 = 1139
67 x 18 = 1206
67 x 19 = 1273
67 x 20 = 1340


68 x 1 = 68
68 x 2 = 136
68 x 3 = 204
68 x 4 = 272
68 x 5 = 340
68 x 6 = 408
68 x 7 = 476
68 x 8 = 544
68 x 9 = 612
68 x 10 = 680
68 x 11 = 748
68 x 12 = 816
68 x 13 = 884
68 x 14 = 952
68 x 15 = 1020
68 x 16 = 1088
68 x 17 = 1156
68 x 18 = 1224
68 x 19 = 1292
68 x 20 = 1360


69 x 1 = 69
69 x 2 = 138
69 x 3 = 207
69 x 4 = 276
69 x 5 = 345
69 x 6 = 414
69 x 7 = 483
69 x 8 = 552
69 x 9 = 621
69 x 10 = 690
69 x 11 = 759
69 x 12 = 828
69 x 13 = 897
69 x 14 = 966
69 x 15 = 1035
69 x 16 = 1104
69 x 17 = 1173
69 x 18 = 1242
69 x 19 = 1311
69 x 20 = 1380


70 x 1 = 70
70 x 2 = 140
70 x 3 = 210
70 x 4 = 280
70 x 5 = 350
70 x 6 = 420
70 x 7 = 490
70 x 8 = 560
70 x 9 = 630
70 x 10 = 700
70 x 11 = 770
70 x 12 = 840
70 x 13 = 910
70 x 14 = 980
70 x 15 = 1050
70 x 16 = 1120
70 x 17 = 1190
70 x 18 = 1260
70 x 19 = 1330
70 x 20 = 1400


71 x 1 = 71
71 x 2 = 142
71 x 3 = 213
71 x 4 = 284
71 x 5 = 355
71 x 6 = 426
71 x 7 = 497
71 x 8 = 568
71 x 9 = 639
71 x 10 = 710
71 x 11 = 781
71 x 12 = 852
71 x 13 = 923
71 x 14 = 994
71 x 15 = 1065
71 x 16 = 1136
71 x 17 = 1207
71 x 18 = 1278
71 x 19 = 1349
71 x 20 = 1420


72 x 1 = 72
72 x 2 = 144
72 x 3 = 216
72 x 4 = 288
72 x 5 = 360
72 x 6 = 432
72 x 7 = 504
72 x 8 = 576
72 x 9 = 648
72 x 10 = 720
72 x 11 = 792
72 x 12 = 864
72 x 13 = 936
72 x 14 = 1008
72 x 15 = 1080
72 x 16 = 1152
72 x 17 = 1224
72 x 18 = 1296
72 x 19 = 1368
72 x 20 = 1440


73 x 1 = 73
73 x 2 = 146
73 x 3 = 219
73 x 4 = 292
73 x 5 = 365
73 x 6 = 438
73 x 7 = 511
73 x 8 = 584
73 x 9 = 657
73 x 10 = 730
73 x 11 = 803
73 x 12 = 876
73 x 13 = 949
73 x 14 = 1022
73 x 15 = 1095
73 x 16 = 1168
73 x 17 = 1241
73 x 18 = 1314
73 x 19 = 1387
73 x 20 = 1460


74 x 1 = 74
74 x 2 = 148
74 x 3 = 222
74 x 4 = 296
74 x 5 = 370
74 x 6 = 444
74 x 7 = 518
74 x 8 = 592
74 x 9 = 666
74 x 10 = 740
74 x 11 = 814
74 x 12 = 888
74 x 13 = 962
74 x 14 = 1036
74 x 15 = 1110
74 x 16 = 1184
74 x 17 = 1258
74 x 18 = 1332
74 x 19 = 1406
74 x 20 = 1480


75 x 1 = 75
75 x 2 = 150
75 x 3 = 225
75 x 4 = 300
75 x 5 = 375
75 x 6 = 450
75 x 7 = 525
75 x 8 = 600
75 x 9 = 675
75 x 10 = 750
75 x 11 = 825
75 x 12 = 900
75 x 13 = 975
75 x 14 = 1050
75 x 15 = 1125
75 x 16 = 1200

#### Iterating over a custoome iterable object

In [33]:
class MyRange:
    def __init__(self, start, stop):
        self.start = start
        self.stop = stop

    def __iter__(self):
        return self

    def __next__(self):
        if self.start >= self.stop:
            raise StopIteration
        value = self.start
        self.start += 1
        return value

In [34]:
# Example usage of custom iterable object with a for loop
my_range = MyRange(1, 6)
for num in my_range:
    print(num)

1
2
3
4
5

# 4. The `else` Suite

- In Python, the `else` suite associated with loops provides a mechanism to execute a block of code after the loop completes its iterations normally, i.e., without encountering a `break` statement or an exception.
- This feature is available for both `for` and `while` loops and offers a way to add additional logic that executes when the loop finishes its operation.

### 4.1. Syntax

In [ ]:
# For `for` loop

for item in iterable:
    # Code block for loop body
else:
    # Code block for else suite

In [ ]:
# For `while` loop:

while condition:
    # Code block for loop body
else:
    # Code block for else suite

### 4.2. Behavior

1. **For `for` loop:**
   - The `else` suite is executed after the loop iterates through all items in the iterable, or if the iterable is empty.
   - It does not execute if the loop is terminated prematurely using a `break` statement.

2. **For `while` loop:**
   - The `else` suite is executed after the loop terminates naturally when the loop condition becomes false.
   - It does not execute if the loop is terminated using a `break` statement or if an exception is raised within the loop.

### 4.3. Use Cases

1. **Iterating Over a Collection:**

In [35]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)
else:
    print("No more fruits to iterate")

apple
banana
cherry
No more fruits to iterate

In this example, the `else` suite executes after the loop iterates through all items in the `fruits` list.

2. **Searching in a While Loop:**

In [36]:
num = 10
while num > 0:
    print(num)
    num -= 1
else:
    print("Loop completed normally")

10
9
8
7
6
5
4
3
2
1
Loop completed normally

   Here, the `else` suite executes after the `while` loop terminates naturally when `num` becomes 0.

### 4.4. Advantages

1. **Readability:**
- The `else` suite enhances the readability of the code by providing a clear indication of the additional logic that executes after the loop.
   
2. **Cleanup Code:**
- It allows for the inclusion of cleanup or finalization code that needs to be executed after the loop has finished its operation.

### 4.5. Limitations

1. **Premature Termination:**
- The `else` suite does not execute if the loop is terminated prematurely using a `break` statement or if an exception is raised within the loop.

# 5. Nested Loop

- A nested loop in Python refers to a loop structure within another loop.
- This means that one loop is contained (nested) within the body of another loop.
- Nested loops are a powerful construct that allows for the repetition of code blocks multiple times, with each iteration of the outer loop triggering multiple iterations of the inner loop.

In [ ]:
# Syntax
for outer_item in outer_sequence:
    # Code block for outer loop body
    for inner_item in inner_sequence:
        # Code block for inner loop body

- The outer loop is typically defined using a `for` loop, but it can also be a `while` loop.
- The inner loop is defined within the body of the outer loop and can also be a `for` or `while` loop.
- The inner loop executes its code block for each iteration of the outer loop.

### 5.1. Execution Flow
1. The outer loop begins its iterations, and for each iteration, the inner loop starts from the beginning.
2. The inner loop completes all its iterations for each iteration of the outer loop.
3. Once the inner loop finishes all its iterations, control returns to the outer loop, which then proceeds to its next iteration.
4. This process continues until the outer loop completes all its iterations.

In [37]:
# Example: Nested loops to print a multiplication table
for i in range(1, 6):       # Outer loop for rows
    for j in range(1, 11):  # Inner loop for columns
        print(i * j, end="\t")
    print()  # Newline after each row

1	2	3	4	5	6	7	8	9	10
2	4	6	8	10	12	14	16	18	20
3	6	9	12	15	18	21	24	27	30
4	8	12	16	20	24	28	32	36	40
5	10	15	20	25	30	35	40	45	50

- In this example, the outer loop (`for i in range(1, 6)`) iterates over the rows of the multiplication table, while the inner loop (`for j in range(1, 11)`) iterates over the columns. 
- For each value of `i` in the outer loop, the inner loop computes and prints the product `i * j` for each value of `j` in the inner loop, resulting in a complete multiplication table.

### 5.2. Advantages of Nested Loops

1. **Complex Iteration Patterns:**
    - Nested loops allow for the creation of complex iteration patterns, where each iteration of the outer loop triggers multiple iterations of the inner loop.

2. **Matrix Operations:** 
- Nested loops are commonly used for matrix operations, such as matrix multiplication, transposition, and element-wise operations.

3. **Search and Traverse Data Structures:**
- Nested loops can be used to search and traverse multidimensional data structures, such as lists of lists or nested dictionaries.

### 5.3. Caveats and Considerations:

1. **Performance:** 
- Nested loops can lead to slower performance, especially if the inner loop has a large number of iterations or if the loops are deeply nested.
- Careful optimization may be necessary in performance-critical code.

2. **Complexity:** 
- Deeply nested loops can make code harder to understand and maintain.
- Consider refactoring complex nested loops into separate functions or using alternative approaches, such as list comprehensions or recursion, when appropriate.

### 5.4. Examples

#### Printing Patterns

In [38]:
row = 1
while row <= 5:
    col = 1
    while col <= row:
        print("*", end=" ")
        col += 1
    print()
    row += 1

*
* *
* * *
* * * *
* * * * *

In [43]:
for i in range(1, 6):
    for j in range(i):
        print("*", end=" ")
    print()

*
* *
* * *
* * * *
* * * * *

#### 2. Generating Prime Numbers

In [40]:
num = 2
while num <= 20:
    prime = True
    divisor = 2
    while divisor <= num // 2:
        if num % divisor == 0:
            prime = False
            break
        divisor += 1
    if prime:
        print(num, "is prime")
    else:
        print(num, "is not prime")
    num += 1

2 is prime
3 is prime
4 is not prime
5 is prime
6 is not prime
7 is prime
8 is not prime
9 is not prime
10 is not prime
11 is prime
12 is not prime
13 is prime
14 is not prime
15 is not prime
16 is not prime
17 is prime
18 is not prime
19 is prime
20 is not prime

#### 3. Matrix Multiplications

In [41]:
matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]
row = 0
while row < len(matrix1):
    col = 0
    while col < len(matrix2[0]):
        for i in range(len(matrix1[0])):
            result[row][col] += matrix1[row][i] * matrix2[i][col]
        col += 1
    row += 1
print(result)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]

#### 4. Generating Fibonacci Sequence

In [44]:
n = 10
fibonacci = [0, 1]
for i in range(2, n):
    fibonacci.append(fibonacci[i - 1] + fibonacci[i - 2])
print(fibonacci)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]